### ISSUE TITLE
Tests fail if jq is not installed

### ISSUE THREAD

**Issue by eserte** [kaz-utashiro/greple-jq#1]
See subject. Sample fail report on CPAN Testers: http://www.cpantesters.org/cpan/report/feb6126c-847c-11ec-bc66-57723b537541

Maybe a missing jq may be detected already during configuration phase (in Makefile.PL or Build.PL) and aborting the installation, so just a NA or UNKNOWN report is sent to CPAN Testers? Or the tests could be skipped if jq is not installed?

**Comment by kaz-utashiro** [comment]
Thank you.  I made test script run without jq command installed.  Hope it works.

**Comment by eserte** [comment]
No more failures with App-Greple-jq-0.05. Thank you.
